services:
 
  postgres:
    image: postgres:16-alpine
    container_name: postgree
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: final
      POSTGRES_DB: transcendence_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/postgresql